/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0xE0, 0x3C, 0x12, 0xFF, 0xC2, 0x2C, 0x1C, 0xA4}

#define VIAL_UNLOCK_COMBO_ROWS { 0, 4 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 4 }

#define DYNAMIC_KEYMAP_LAYER_COUNT 10

#define VIAL_TAP_DANCE_ENTRIES 100
#define DYNAMIC_KEYMAP_MACRO_COUNT 100
#define VIAL_COMBO_ENTRIES 100