/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0xE0, 0x3C, 0x12, 0xFF, 0xC2, 0x2C, 0x1C, 0xA4}

#define VIAL_UNLOCK_COMBO_ROWS { 0, 4 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 4 }

#undef DYNAMIC_KEYMAP_LAYER_COUNT
#define DYNAMIC_KEYMAP_LAYER_COUNT 15
#define VIAL_TAP_DANCE_ENTRIES 100
#define DYNAMIC_KEYMAP_MACRO_COUNT 75
#define VIAL_COMBO_ENTRIES 75

#undef POINTING_DEVICE_ROTATION_180
#undef POINTING_DEVICE_INVERT_Y_RIGHT
#define POINTING_DEVICE_INVERT_X_RIGHT
#undef POINTING_DEVICE_INVERT_Y
#undef POINTING_DEVICE_INVERT_X

#undef POINTING_DEVICE_AUTO_MOUSE_ENABLE
#undef CHARYBDIS_DRAGSCROLL_DPI
#define CHARYBDIS_DRAGSCROLL_DPI 1

// #undef RGBLIGHT_EFFECT_ALTERNATING
// #undef RGBLIGHT_EFFECT_BREATHING
// #undef RGBLIGHT_EFFECT_RAINBOW_MOOD
// #undef RGBLIGHT_EFFECT_RAINBOW_SWIRL
// #undef RGBLIGHT_EFFECT_SNAKE
// #undef RGBLIGHT_EFFECT_STATIC_GRADIENT
// #undef RGBLIGHT_EFFECT_TWINKLE
